# Generated by Django 5.0.4 on 2024-05-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaDeInicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo_user',
        ),
    ]
