# Generated by Django 5.0.4 on 2024-04-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaDeInicio', '0003_remove_usuario_apellidos_remove_usuario_nombres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
    ]
