# Generated by Django 5.0.4 on 2024-04-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaDeInicio', '0004_remove_usuario_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
