# Generated by Django 5.0.4 on 2024-04-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaDeInicio', '0005_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
