# Generated by Django 5.0.4 on 2024-04-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaDeInicio', '0007_alter_usuario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Mascuilo'), ('B', 'Helicopteer')], max_length=1),
        ),
    ]
