# Generated by Django 5.0.4 on 2024-05-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=500)),
                ('task_description', models.CharField(max_length=700)),
                ('task_type', models.CharField(max_length=500)),
                ('task_assignment_date', models.DateField()),
                ('task_finish_date', models.DateField()),
                ('task_status', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'En progreso'), (2, 'Completada')])),
                ('task_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_work', models.CharField(max_length=500)),
                ('location_work', models.CharField(max_length=500)),
                ('type_work', models.CharField(max_length=500)),
                ('description_work', models.CharField(max_length=500)),
                ('work_status', models.FloatField()),
                ('enabled_work', models.BooleanField(default=True)),
            ],
        ),
    ]
