# Generated by Django 5.0.4 on 2024-05-01 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crud', '0001_initial'),
        ('paginaDeInicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_foreman',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_como_capataz', to='paginaDeInicio.user'),
        ),
        migrations.AddField(
            model_name='task',
            name='id_workers',
            field=models.ManyToManyField(related_name='tareas_asignadas', to='paginaDeInicio.user'),
        ),
        migrations.AddField(
            model_name='work',
            name='id_manager_work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obras_dirigidas', to='paginaDeInicio.user'),
        ),
        migrations.AddField(
            model_name='work',
            name='id_user_work',
            field=models.ManyToManyField(related_name='obras_asignadas', to='paginaDeInicio.user'),
        ),
        migrations.AddField(
            model_name='task',
            name='id_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_obra', to='crud.work'),
        ),
    ]
