# Generated by Django 5.0.4 on 2024-05-19 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_work_id_manager_work'),
        ('paginaDeInicio', '0002_remove_user_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id_foreman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_como_capataz', to='paginaDeInicio.user'),
        ),
    ]
