# Generated by Django 5.0.4 on 2024-05-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_task_id_foreman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_status',
            field=models.FloatField(default=0),
        ),
    ]
