# Generated by Django 5.0.4 on 2024-05-20 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_work_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprogress',
            name='task_progress_id_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='avances_con_tareas', to='crud.task'),
            preserve_default=False,
        ),
    ]
