# Generated by Django 5.0.4 on 2024-05-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_taskprogress_task_progress_id_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_finish_date',
            field=models.DateField(default=None),
        ),
    ]
