# Generated by Django 5.0.3 on 2024-04-26 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paginaDeInicio', '0008_alter_usuario_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('ubicacion', models.CharField(max_length=500)),
                ('tipo', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=500)),
                ('estado_de_obra', models.FloatField()),
                ('habilitado', models.BooleanField(default=True)),
                ('id_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_dirigidas', to='paginaDeInicio.usuario')),
                ('id_usuarios', models.ManyToManyField(related_name='obras_asignadas', to='paginaDeInicio.usuario')),
            ],
        ),
    ]
