# Generated by Django 5.0.4 on 2024-04-09 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaDeInicio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proyecto',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginaDeInicio.rol'),
        ),
    ]
