# Generated by Django 5.0.4 on 2024-04-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaDeInicio', '0002_delete_proyecto_alter_usuario_fotografia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombres',
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/imagenes/'),
        ),
    ]
